# Generated by Gabriel Da Costa on 2022-10-12 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO main.profiles_profile
            SELECT * FROM main.oc_lettings_site_profile;
        """)
    ]
