# CircleCi version
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: tests
          command: pytest
      - run:
          name: linting PEP8
          command: flake8

  build_docker_push:
    docker:
        - image: cimg/python:3.9.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
            docker tag $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1 $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest

workflows:
  master:
    jobs:
      - build-and-test
      - build_docker_push:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master