# CircleCi version
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Run Tests
          command: pytest
          env:
            SENTRY_DSN: $SENTRY_DSN
      - run:
          name: Run Linting PEP8
          command: flake8

  build-docker-push:
    docker:
      - image: cimg/python:3.9.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
            docker tag $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1 $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$CIRCLE_SHA1
            docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest

  deploy-heroku:
    docker:
      - image: cimg/python:3.9.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start container and push to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            export HEROKU_API_KEY=$HEROKU_API_KEY
            heroku container:login
            heroku maintenance:on --app $HEROKU_APP_NAME
            heroku config:set DJANGO_ALLOWED_HOSTS=$HEROKU_APP_NAME.herokuapp.com --app $HEROKU_APP_NAME
            heroku config:set SENTRY_DSN=$SENTRY_DSN -a $HEROKU_APP_NAME
            heroku stack:set heroku-20 -a $HEROKU_APP_NAME
            heroku maintenance:off --app $HEROKU_APP_NAME
            heroku container:push -a $HEROKU_APP_NAME web
            heroku container:release -a $HEROKU_APP_NAME web

workflows:
  master:
    jobs:
      - build-and-test
      - build-docker-push:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - deploy-heroku:
          requires:
            - build-docker-push
          filters:
            branches:
              only:
                - master