# CircleCi version
version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.1.4

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: pytest
          name: run pytest
      - run:
          command: flake8
          name: run flake8





workflows:
  master:
    jobs:
      - build-and-test

      - docker/publish:
          image: gabrielbusiness2019/oc_lettings_site_build
          tag: '$CIRCLE_SHA1,latest'
          # Publish to dockerhub only if branch master
          filters:
            branches:
              only: master