# Generated by Gabriel Da Costa on 2022-10-13 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('oc_lettings_site', '0003_auto_20221012_1002'),
        ('lettings', '0003_restore_data_letting'),
        ('profiles', '0002_restore_data_profile'),

    ]

    operations = [
        migrations.RunSQL("""
            DROP TABLE oc_lettings_site_address;
            DROP TABLE oc_lettings_site_letting;
            DROP TABLE oc_lettings_site_profile;
        """)
    ]
