# Generated by Gabriel Da Costa on 2022-10-12 09:

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO lettings_address
            SELECT id, number, street, city, state, zip_code, country_iso_code
            FROM oc_lettings_site_address;
        """)
    ]
