# Generated by Gabriel Da Costa on 2022-10-12 09:

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('lettings', '0002_restore_data_address'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO lettings_letting
            SELECT id, title, address_id 
            FROM oc_lettings_site_letting;
        """)
    ]
